### ISSUE TITLE
osx-arm64 build missing

### ISSUE THREAD

**Issue by rgommers** [conda-forge/doit-feedstock#16]
See https://anaconda.org/conda-forge/doit, only 64-bit Linux/Windows/macOS on `x86_64` are present for `doit` 0.35.0. Looking at the recipe, the `osx`-specific dependency is `macfsevents`, which also only has a `x86_64` build. A PR is open for that: https://github.com/conda-forge/macfsevents-feedstock/pull/12

Questions: is the above it, or is there another blocker?

**Comment by bollwyvl** [comment]
As noted over on https://github.com/conda-forge/macfsevents-feedstock/pull/12#issuecomment-1095016525, that upstream appears pretty much abandoned, and doesn't work with modern python.

So hopefully we get that dependency cut out over on https://github.com/pydoit/doit/issues/424, which would make this `noarch`, and get all the arm/ppc platforms for free.

**Comment by bollwyvl** [comment]
#18 was just merged, making everything noarch, so doit should be installable from conda-forge on osx-arm64 within 1-2 hours.

please open a new if any issues persist, as whether it _works_ on osx-arm64 is a whole other story.

**Comment by rgommers** [comment]
Awesome 🎉

**Comment by rgommers** [comment]
and works for me!
